Repository ROCm/omnitrace, pull requests merged in 2022-06, with the labels that each got.

#23 New documentation page with youtube links to tutorials
  source/docs/index.md
  source/docs/youtube.md
Labels: documentation

#26 Update setup-env.sh and modulefile
  cmake/Templates/modulefile.in
  cmake/Templates/setup-env.sh.in
Labels: bug fix

#28 Fix perfetto_counter_track string lifetime
  source/lib/omnitrace/library/perfetto.hpp
Labels: bug fix, perfetto, sampling, thread sampling, rocm-smi, testing

#29 Set OMNITRACE_USE_THREAD_SAMPLING=ON for several tests
  tests/CMakeLists.txt
Labels: testing

#25 Fix category regex + new features
  source/bin/omnitrace-avail/avail.cpp
  source/bin/tests/CMakeLists.txt
Labels: enhancement, bug fix, omnitrace-avail, testing

#30 Rework sampling trace counter names + new trace counters
  source/lib/omnitrace/library/components/backtrace.cpp
  source/lib/omnitrace/library/components/backtrace.hpp
  source/lib/omnitrace/library/components/rocm_smi.cpp
  source/lib/omnitrace/library/cpu_freq.cpp
Labels: enhancement, perfetto, libomnitrace, sampling, thread sampling

#32 Fix loop-level instrumentation + more
  examples/transpose/transpose.cpp
  source/bin/omnitrace/details.cpp
  source/bin/omnitrace/function_signature.cpp
  source/bin/omnitrace/function_signature.hpp
  source/bin/omnitrace/module_function.cpp
  source/bin/omnitrace/module_function.hpp
  source/bin/omnitrace/omnitrace.cpp
  source/bin/omnitrace/omnitrace.hpp
  tests/CMakeLists.txt
Labels: enhancement, bug fix, omnitrace, binary instrumentation, testing, examples

#33 Fix sampling counter time scales
  source/lib/omnitrace/library.cpp
  source/lib/omnitrace/library/components/backtrace.cpp
  source/lib/omnitrace/library/components/backtrace.hpp
  source/lib/omnitrace/library/components/pthread_create_gotcha.cpp
  source/lib/omnitrace/library/components/pthread_create_gotcha.hpp
  source/lib/omnitrace/library/components/rocm_smi.cpp
  source/lib/omnitrace/library/components/roctracer_callbacks.cpp
  source/lib/omnitrace/library/cpu_freq.cpp
  source/lib/omnitrace/library/critical_trace.cpp
Labels: bug fix, perfetto, sampling, thread sampling

#34 Implements --label option for python profiler
  VERSION
  source/docs/python.md
  source/python/omnitrace/__main__.py
  tests/CMakeLists.txt
Labels: documentation, omnitrace-python, testing

#37 Support omnitrace-dl as kokkos profile library
  cmake/MacroUtilities.cmake
  scripts/dl-gen.py
  source/lib/omnitrace-dl/dl.cpp
  source/lib/omnitrace-dl/dl.hpp
  source/lib/omnitrace/library/kokkosp.cpp
Labels: enhancement, libomnitrace-dl, KokkosP, cmake

#39 Fix the main library stop routine for timemory
  .github/workflows/ubuntu-bionic.yml
  .github/workflows/ubuntu-focal-external-rocm.yml
  .github/workflows/ubuntu-focal-external.yml
  .github/workflows/ubuntu-focal.yml
  VERSION
  source/docs/features.md
  source/docs/python.md
  source/docs/user_api.md
  source/lib/omnitrace/library.cpp
  source/lib/omnitrace/library/components/pthread_create_gotcha.cpp
  tests/CMakeLists.txt
  tests/validate-timemory-json.py
Labels: documentation, bug fix, timemory, libomnitrace, testing

#50 Fixes excluded-instr output, fini functions, tweaks MPI
  cmake/Packages.cmake
  source/bin/omnitrace/omnitrace.cpp
  source/bin/tests/CMakeLists.txt
Labels: bug fix, omnitrace, binary instrumentation, testing

#55 Define new function attributes
  source/lib/omnitrace/library/config.hpp
  source/lib/omnitrace/library/debug.hpp
  source/lib/omnitrace/library/defines.hpp.in
  source/lib/omnitrace/library/redirect.hpp
  source/lib/omnitrace/library/runtime.hpp
Labels: libomnitrace

#54 Inclusive range for OMNITRACE_SAMPLING_CPUS
  source/lib/omnitrace/library/cpu_freq.cpp
Labels: libomnitrace, configuration

#53 Fixes OMNITRACE_SUPPRESS_CONFIG handling
  source/lib/omnitrace/library/config.cpp
Labels: bug fix, libomnitrace

#56 Remove reliance on MPI_Comm_rank
  examples/mpi/mpi.cpp
  source/lib/omnitrace/CMakeLists.txt
  source/lib/omnitrace/library/components/mpi_gotcha.cpp
  source/lib/omnitrace/library/mproc.cpp
  source/lib/omnitrace/library/mproc.hpp
Labels: libomnitrace

#59 Fix find_path in omnitrace-dl
  source/lib/common/invoke.hpp
  source/lib/common/join.hpp
  source/lib/omnitrace-dl/dl.cpp
Labels: bug fix, libomnitrace-dl

#61 Improved the determination of MPI rank
  examples/mpi/mpi.cpp
  source/lib/omnitrace/library/components/mpi_gotcha.cpp
  source/lib/omnitrace/library/components/mpi_gotcha.hpp
  source/lib/omnitrace/library/debug.hpp
Labels: bug fix, libomnitrace

#60 Fix attaching to running process, i.e. omnitrace -p <PID>
  source/bin/omnitrace/omnitrace.cpp
  tests/CMakeLists.txt
  tests/run-omnitrace-pid.sh
Labels: omnitrace, binary instrumentation, testing

#58 Rename OMNITRACE_ROCM_SMI_DEVICES to OMNITRACE_SAMPLING_GPUS
  VERSION
  source/docs/runtime.md
  source/lib/omnitrace/library/components/rocm_smi.cpp
  source/lib/omnitrace/library/config.cpp
  source/lib/omnitrace/library/config.hpp
Labels: documentation, libomnitrace, thread sampling, configuration

#62 libomnitrace uses common headers
  source/lib/common/CMakeLists.txt
  source/lib/common/defines.h
  source/lib/omnitrace/CMakeLists.txt
  source/lib/omnitrace/library/common.hpp
  source/lib/omnitrace/library/defines.hpp.in
  source/lib/omnitrace/library/mproc.cpp
  source/lib/omnitrace/library/timemory.hpp
Labels: libomnitrace, cmake

#66 adding perfetto-validation-script
  .cmake-format.yaml
  .github/workflows/formatting.yml
  .github/workflows/opensuse.yml
  .github/workflows/ubuntu-bionic.yml
  .github/workflows/ubuntu-focal-external-rocm.yml
  .github/workflows/ubuntu-focal-external.yml
  .github/workflows/ubuntu-focal.yml
  examples/python/builtin.py
  examples/python/external.py
  examples/python/source.py
  pyproject.toml
  source/docs/conf.py
  source/python/omnitrace/profiler.py
  tests/CMakeLists.txt
  tests/validate-perfetto-proto.py
  tests/validate-timemory-json.py
Labels: perfetto, omnitrace-python, testing

#71 Fix PID resolution + OMNITRACE_VERSION + fix various configs
  source/lib/omnitrace/library/components/mpi_gotcha.cpp
  source/lib/omnitrace/library/components/roctracer_callbacks.cpp
  source/lib/omnitrace/library/config.cpp
  source/lib/omnitrace/library/defines.hpp.in
  tests/CMakeLists.txt
Labels: bug fix, perfetto, configuration

#73 Fix docs using -D instead of -G
  README.md
  source/docs/runtime.md
Labels: documentation

#77 Use concurrency in GitHub Actions + remove cancelling
  .github/workflows/cancelling.yml
  .github/workflows/cpack-opensuse.yml
  .github/workflows/cpack-ubuntu.yml
  .github/workflows/formatting.yml
  .github/workflows/opensuse.yml
  .github/workflows/ubuntu-bionic.yml
  .github/workflows/ubuntu-focal-external-rocm.yml
  .github/workflows/ubuntu-focal-external.yml
  .github/workflows/ubuntu-focal.yml
  README.md
Labels: testing
